In [4]:
from medgenius.extract_tables_and_images import extract_tables
from IPython.display import display



for i in range(1, 144):
    print(f'page : {i}')
    for d in extract_tables(pdf_path='./data/pdf_2.pdf', page_number=i):
        display(d)

page : 1

c:\Users\82103\anaconda3\Lib\site-packages\camelot\parsers\lattice.py:392: UserWarning: page-1 is image-based, camelot only works on text-based pages.
  warnings.warn(

page : 2
page : 3
page : 4
page : 5

c:\Users\82103\anaconda3\Lib\site-packages\camelot\parsers\lattice.py:397: UserWarning: No tables found on page-4
  warnings.warn(

page : 6
page : 7

c:\Users\82103\anaconda3\Lib\site-packages\camelot\parsers\lattice.py:397: UserWarning: No tables found on page-6
  warnings.warn(

page : 8
page : 9
page : 10
page : 11
page : 12
page : 13
page : 14
page : 15
page : 16
page : 17

c:\Users\82103\anaconda3\Lib\site-packages\camelot\parsers\lattice.py:397: UserWarning: No tables found on page-16
  warnings.warn(

page : 18
page : 19

c:\Users\82103\anaconda3\Lib\site-packages\camelot\parsers\lattice.py:397: UserWarning: No tables found on page-18
  warnings.warn(

         0                                            1
0  권고  적용군  심뇌혈관질환  또는  고혈압  또는  당뇨병을  진단받은  환자진료환경의료기관
1  중재/실행지표                                     지질검사  시행
2     비교지표                                    지질검사  미시행
3      결과물                                   심뇌혈관질환  예방

                                                   0     1     2         3
0                                             권고  내용  권고등급  근거수준  권고도출 자료원
1   다음과  같은  질환을  진단받은  경우  지질검사  시행을  권고한다.a),b...     I     D     1,  2

page : 20

         0                           1
0  권고  적용군  모든  성인(만  19세  이상)진료환경의료기관
1  중재/실행지표                    지질검사  시행
2     비교지표                   지질검사  미시행
3      결과물                  이상지질혈증  진단

                                                   0     1     2          3
0                                             권고  내용  권고등급  근거수준  권고도출  자료원
1   다음과  같은  심뇌혈관질환  위험인자를  가진  경우  지질검사  시행을  권...     I     D          2
2    모든  성인은  심뇌혈관질환  위험인자가  없더라도  지질검사  시행을  고려한다.   IIa     D          2

page : 21
page : 22

         0                                                 1
0  권고  적용군                            모든  이상지질혈증  환자진료환경의료기관
1  중재/실행지표   총콜레스테롤,  중성지방,  HDL  콜레스테롤,  LDL  콜레스테롤  검사  시행
2     비교지표  총콜레스테롤,  중성지방,  HDL  콜레스테롤,  LDL  콜레스테롤  검사  미시행
3      결과물                                        이상지질혈증  진단

                                                   0     1     2          3
0                                             권고  내용  권고등급  근거수준  권고도출  자료원
1   심뇌혈관질환 발생 위험을 평가하기 위하여 총콜레스테롤, 중성지방, HDL 콜레스...     I     D        1-4
2   중성지방이  400  mg/dL  이상인  경우  LDL  콜레스테롤  직접  ...     I     D          2

page : 23
page : 24

        0        1
0  매우  높음   ≥  500
1      높음  200-499
2     경계치  150-199
3      적정   ＜  150

        0        1
0  매우  높음   ≥  190
1      높음  160-189
2     경계치  130-159
3      정상  100-129
4      적정   ＜  100

page : 25
page : 26
page : 27

c:\Users\82103\anaconda3\Lib\site-packages\camelot\parsers\lattice.py:397: UserWarning: No tables found on page-26
  warnings.warn(

page : 28
page : 29

c:\Users\82103\anaconda3\Lib\site-packages\camelot\parsers\lattice.py:397: UserWarning: No tables found on page-28
  warnings.warn(

         0                                                  1
0  권고  적용군                                 관상동맥질환  환자진료환경의료기관
1  중재/실행지표  LDL  콜레스테롤  55  mg/dL  미만  그리고  기저치보다  50%  이상...
2     비교지표                          LDL  콜레스테롤  55  mg/dL  이상
3      결과물                                    심뇌혈관질환  위험도  감소

                                                   0     1     2          3
0                                             권고  내용  권고등급  근거수준  권고도출  자료원
1   관상동맥질환이 있는 환자는 이차 예방을 위해 LDL 콜레스테롤 농도를 55 mg...     I     A        1-4

page : 30
page : 31

         0                                       1
0  권고  적용군  관상동맥질환을  제외한  죽상경화성  심혈관질환  환자진료환경의료기관
1  중재/실행지표         LDL  콜레스테롤  70  mg/dL  미만으로  조절
2     비교지표               LDL  콜레스테롤  70  mg/dL  이상
3      결과물                         심뇌혈관질환  위험도  감소

                                                   0     1     2          3
0                                             권고  내용  권고등급  근거수준  권고도출  자료원
1  LDL 콜레스테롤 70 mg/dL 미만 그리고 기저치보다 50% 이상 감소를 목표...     I     A        5-9

page : 32
page : 33
page : 34
page : 35
page : 36

         0                                 1
0  권고  적용군                   당뇨병  환자진료환경의료기관
1  중재/실행지표  LDL  콜레스테롤  100  mg/dL  미만으로  조절
2     비교지표        LDL  콜레스테롤  100  mg/dL  이상
3      결과물                   심뇌혈관질환  위험도  감소

,0,1,2,3
0,권고 내용,권고등급,근거수준,권고도출 자료원
1, 유병 기간이 10년 미만이고 주요 심혈관질환 위험인자를 동반하지 않은 당뇨병 환...,I,A,"10-122, 11, 1311, 14"
2, 유병 기간이 10년 이상이거나 주요 심혈관질환 위험인자 또는 표적장기손상(알부민...,I,B,
3, 표적장기손상이나 3개 이상의 주요 심혈관질환 위험인자를 동반한 당뇨병 환자는 L...,Ⅱa,B,

page : 37
page : 38

         0                                 1
0  권고  적용군                중등도위험군  환자진료환경의료기관
1  중재/실행지표  LDL  콜레스테롤  130  mg/dL  미만으로  조절
2     비교지표        LDL  콜레스테롤  130  mg/dL  이상
3      결과물                   심뇌혈관질환  위험도  감소

                                                   0     1     2          3
0                                             권고  내용  권고등급  근거수준  권고도출  자료원
1   중등도위험군  환자의  경우  LDL  콜레스테롤  130  mg/dL  미만으...   IIa     B      15-22

page : 39

         0                                 1
0  권고  적용군                  저위험군  환자진료환경의료기관
1  중재/실행지표  LDL  콜레스테롤  160  mg/dL  미만으로  조절
2     비교지표        LDL  콜레스테롤  160  mg/dL  이상
3      결과물                   심뇌혈관질환  위험도  감소

page : 40
page : 41

         0                                       1
0  권고  적용군  중성지방  농도가  500  mg/dL  이상인  경우진료환경의료기관
1  중재/실행지표         중성지방  농도를  500  mg/dL  미만으로  조절
2     비교지표               중성지방  농도를  500  mg/dL  이상
3      결과물                             췌장염  발생  예방

                                                   0     1     2          3
0                                             권고  내용  권고등급  근거수준  권고도출  자료원
1   혈중  중성지방  농도가  500  mg/dL  이상인  경우,  중성지방을  ...     I     D          9
2   중성지방 농도가 지속적으로 500 mg/dL 이상인 경우, 급성췌장염을 예방하기...   IIa     D      23-26

page : 42

         0                                       1
0  권고  적용군  중성지방  농도가  200-499  mg/dL인  경우진료환경의료기관
1  중재/실행지표              피브린산  유도체  또는  오메가  3  지방산
2     비교지표                                      위약
3      결과물                         심뇌혈관질환  위험도  감소

                                                   0     1     2            3
0                                             권고  내용  권고등급  근거수준    권고도출  자료원
1   혈중  중성지방  농도가  200  mg/dL  이상으로  상승되어  있는  경...     I     D       9,  27
2   생활 습관 개선 후에도 중성지방 농도가 200-499 mg/dL이면서 LDL 콜...     I     A  9,  27,  28
3   죽상경화성 심혈관질환이나 당뇨병 환자에서 생활 습관 개선 및 스타틴 투약 후에도...   IIb     B           29
4   죽상경화성 심혈관질환이나 당뇨병 환자에서 생활 습관 개선 및 스타틴 투약 후에도...   IIb     D        30-33
5   죽상경화성 심혈관질환이나 당뇨병 환자에서 생활 습관 개선 및 스타틴 투약 후에도...   IIb     D      29,  34

page : 43
page : 44
page : 45

         0                                                  1
0  권고  적용군  HDL  콜레스테롤  농도가  낮은  경우진료환경의료기관(남성  40  mg/dL,...
1  중재/실행지표  HDL  콜레스테롤  남성  40  mg/dL,  여성  50  mg/dL  이상으...
2     비교지표  HDL  콜레스테롤  남성  40  mg/dL,  여성  50  mg/dL  이상으...
3      결과물                            심뇌혈관질환  위험도  감소a),c),d)

page : 46
page : 47
page : 48

         0                                                  1
0  권고  적용군  약물을  투여한  후에도  LDL  콜레스테롤  농도가  치료  목표에 진료환경의료...
1  중재/실행지표                  약물의  용량을  최대한  증량시켜서  치료  목표에  도달
2     비교지표              치료  목표에  도달하기  위해  약물  용량을  증량시키지  않음
3      결과물                                    심뇌혈관질환  위험도  감소

                                                   0     1     2          3
0                                             권고  내용  권고등급  근거수준  권고도출  자료원
1   스타틴을  투여한  후에도  LDL  콜레스테롤  농도가  치료  목표에  도달...     I     A  5,  47-56

page : 49

         0                                                  1
0  권고  적용군  약물을  투여한  후에도  LDL  콜레스테롤  농도가  치료  목표에 진료환경의료...
1  중재/실행지표                         다른  약물을  병용하여  치료  목표에  도달
2     비교지표                                  다른  약물을  병용하지  않음
3      결과물                                    심뇌혈관질환  위험도  감소

,0,1,2,3
0,권고 내용,권고등급,근거수준,권고도출 자료원
1, 스타틴을 투여한 후에도 LDL 콜레스테롤 농도가 치료 목표에 도달...,I,A,"1, 13, 47-56"

page : 50
page : 51
page : 52

         0                                     1
0  권고  적용군  이상지질혈증  약물  치료  4-12주  후  환자진료환경의료기관
1  중재/실행지표                        혈중  지질  농도  측정
2     비교지표                  혈중  지질  농도  측정하지  않음
3      결과물                    치료  목표  도달  여부  평가

,0,1,2,3
0,권고 내용,권고등급,근거수준,권고도출 자료원
1, 이상지질혈증 약물 치료 전과 치료 4-12주 후 혈중 지질 농도...,I,A,"6, 7, 50, 57-72"

page : 53
page : 54

         0                                     1
0  권고  적용군  이상지질혈증  약물  치료  4-12주  후  환자진료환경의료기관
1  중재/실행지표                     혈중  간  효소  수치  측정
2     비교지표               혈중  간  효소  수치  측정하지  않음
3      결과물                        간  관련  부작용  예방

,0,1,2,3
0,권고 내용,권고등급,근거수준,권고도출 자료원
1, 이상지질혈증 약물 치료 전과 치료 4-12주 후 혈중에서 간 효소 수치 측정을 ...,IIb,B,"12, 27, 7073-76"

page : 55
page : 56

         0                                    1
0  권고  적용군        이상지질혈증  약물  치료  후  환자진료환경의료기관
1  중재/실행지표  혈중  근육효소(Cratine  Kinase,  CK)를  측정
2     비교지표                  혈중  근육효소를  측정하지  않음
3      결과물                      근육  관련  부작용  예방

,0,1,2,3
0,권고 내용,권고등급,근거수준,권고도출 자료원
1," 이상지질혈증 약물 치료 과정 중에 근육 관련 증상(근육통, 근 쇠약감)을 호소할...",IIa,C,"56, 70, 73, 77-80"

page : 57
page : 58
page : 59
page : 60
page : 61
page : 62
page : 63
page : 64
page : 65

c:\Users\82103\anaconda3\Lib\site-packages\camelot\parsers\lattice.py:397: UserWarning: No tables found on page-64
  warnings.warn(

page : 66
page : 67

c:\Users\82103\anaconda3\Lib\site-packages\camelot\parsers\lattice.py:397: UserWarning: No tables found on page-66
  warnings.warn(

         0                                           1
0  권고  적용군               이상지질혈증으로  진단된  모든  환자진료환경의료기관
1  중재/실행지표        치료적  생활  습관  개선을  병행하는  포괄적인  방법  시행
2     비교지표  치료적  생활  습관  개선을  병행하는  포괄적인  방법  시행하지  않음
3      결과물                                   심혈관질환  예방

                                                   0     1     2          3
0                                             권고  내용  권고등급  근거수준  권고도출  자료원
1   이상지질혈증과  이와  관련된  대사이상  및  심혈관  위험인자를  조절하기 ...     I     D          1

page : 68
page : 69

         0                              1
0  권고  적용군  이상지질혈증으로  진단된  모든  환자진료환경의료기관
1  중재/실행지표                  포화지방산  섭취  감량
2     비교지표                  포화지방산  섭취  유지
3      결과물            LDL  콜레스테롤  수치의  개선

                                                   0     1     2          3
0                                             권고  내용  권고등급  근거수준  권고도출  자료원
1                        포화지방산  섭취를  제한하도록  권고한다.a)     I     A        2-7
2                     트랜스지방산  섭취를  피하는  것을  권고한다.a)     I     A        7-9
3   포화지방산  섭취를  줄이기  위해  단일  또는  다가불포화지방산  섭취로  ...    Ⅱa     B     6,  10
4   알코올은  하루  1–2잔  이내로  제한하며,  가급적  금주할  것을  권고...     I     B         11
5   총탄수화물  섭취량을  에너지  섭취량의  65%  이내로  과다하지  않도록 ...    Ⅱa     B    12,  13

page : 70
page : 71
page : 72

         0                                 1
0  권고  적용군     이상지질혈증으로  진단된  모든  환자진료환경의료기관
1  중재/실행지표                   불포화지방산  적정량  섭취
2     비교지표                     포화지방산  위주  섭취
3      결과물  심뇌혈관질환으로  인한  입원율  증가와  사망률의  개선

,0,1,2,3
0,권고 내용,권고등급,근거수준,권고도출 자료원
1, 심뇌혈관질환 합병증 예방을 위해 포화지방산 섭취를 제한하도록 고려한...,IIa,A,"7, 14-16"
2, 심뇌혈관질환 합병증 예방을 위해 포화지방산을 단일 또는 다가불포화지방산 섭취로 ...,IIa,A,"7, 10, 14, 15, 17"

page : 73

         0                                                  1
0  권고  적용군                                 이상지질혈증  환자진료환경의료기관
1  중재/실행지표                                 이상지질혈증  식사  교육  시행
2     비교지표                           이상지질혈증  식사  교육  시행하지  않음
3      결과물  혈중  총콜레스테롤,  중성지방,  LDL  콜레스테롤,  HDL  콜레스테롤  수...

page : 74

         0                                                  1
0  권고  적용군                      이상지질혈증으로  진단된  모든  환자진료환경의료기관
1  중재/실행지표                          주  3회  이상의  규칙적인  유산소  운동
2     비교지표                    주  3회  이상의  규칙적인  유산소  운동  안  함
3      결과물  혈중 총콜레스테롤, 중성지방, LDL 콜레스테롤, HDL 콜레스테롤 수치의 개선, ...

,0,1,2,3
0,권고 내용,권고등급,근거수준,권고도출 자료원
1, 이상지질혈증 환자의 심혈관질환 위험도를 감소시키기 위하여 주 4-6...,I,D,"2, 22-25"
2, 심뇌혈관질환 합병증 예방을 위해 주 3회 이상의 규칙적인 운동을 ...,I,B,"14, 17,26-29"
3, 이상지질혈증 개선을 위해 체중 감량을 고려한다.c),IIa,B,"22, 30-32"

page : 75
page : 76
page : 77

         0                                                  1
0  권고  적용군                      이상지질혈증으로  진단된  모든  환자진료환경의료기관
1  중재/실행지표                                             음주  제한
2     비교지표                                         음주  제한  없음
3      결과물  혈중  총콜레스테롤,  중성지방,  LDL  콜레스테롤,  HDL  콜레스테롤  수...

,0,1,2,3
0,권고 내용,권고등급,근거수준,권고도출 자료원
1, 중성지방이 상승된 환자에서 알코올 섭취를 제한할 것을 권고한다.a),I,A,"11, 26"
2, 중성지방이 상승되어 있지 않은 경우 알코올 섭취는 남성 1일 20-30 g 미만...,I,A,"11, 14, 17, 22, 26, 33-39"
3, 심혈관계 질환 예방을 위해 음주는 1주일에 100 g 이하로 제한하고 가급적 금...,I,B,"40, 41"

page : 78
page : 79

         0                                                  1
0  권고  적용군                      이상지질혈증으로  진단된  모든  환자진료환경의료기관
1  중재/실행지표                                                 금연
2     비교지표                                                 흡연
3      결과물  심뇌혈관질환  합병증(협심증,  심근경색,  심뇌혈관질환  악화로  인한  입원, ...

,0,1,2,3
0,권고 내용,권고등급,근거수준,권고도출 자료원
1, 직접 및 간접흡연을 포함한 흡연 노출은 심뇌혈관질환의 위험을 증가...,I,A,"14, 15, 17, 2642-53"

page : 80
page : 81
page : 82
page : 83
page : 84
page : 85
page : 86

c:\Users\82103\anaconda3\Lib\site-packages\camelot\parsers\lattice.py:397: UserWarning: No tables found on page-86
  warnings.warn(

page : 87

         0                               1
0  권고  적용군  약물치료가  필요한  이상지질혈증  환자진료환경의료기관
1  중재/실행지표                         약제의  투약
2     비교지표               약제를  투약하지  않은  경우
3      결과물          심뇌혈관질환의  예방  및  재발  방지

,0,1,2,3
0,권고 내용,권고등급,근거수준,권고도출 자료원
1, 급성심근경색증 환자에게서는 LDL 콜레스테롤 농도와 상관없이 스타틴 사용을 권고...,I,A,1-4
2, 고위험군 환자의 경우 생활 습관의 교정과 동시에 스타틴 사용을 ...,I,A,"1, 2,5-11"
3, 저위험군 또는 중등도위험군 환자의 경우 수 주 내지 수 개월간 생활 습관의 교정...,I,A,"1, 2, 12, 13"
4," 스타틴 외의 약제는 콜레스테롤 흡수억제제(에제티미브, Ezetimibe...",IIb,B,"1, 2, 14, 15,16-30"

page : 88
page : 89
page : 90

,0,1,2,3,4,5,6,7,8
0,,,Lovastatin,Pravastatin,Simvastatin,Atorvastatin,Fluvastatin,Rosuvastatin,Pitavastatin
1,하루 사용 용량 (mg),,20-40,10-401),20-40,10-80,20-80,5-202),1-4
2,LDL-C감소(%),24-28,20,20,,,40,,1
3,,30-36,40,40,20,10,80,,2
4,,39-45,80,,40,20,,5-10,4
5,,46-52,,,,40-80,,20,
6,대사경로,,CYP3A4,설폰화,CYP3A4,CYP3A4,CYP2C9,CYP2C9,Glucuronidation(일부CYP2C9)
7,단백질 결합 (%),,＞95,43-67,95-98,98,98,88,＞99
8,반감기 (시간),,2-4,2-3,1-3,13-30,0.5-3,19,12
9,"친수성 (+,-)",,-,+,-,-,-,+,-
10,제거경로,,간담도계,간담도계,간담도계,간담도계,간담도계,간담도계,간담도계
11,흡수량중신장배설 (%),,10,20,13,＜2,＜6,28,15

page : 91
page : 92

         0                                         1
0  권고  적용군  치료  목표  미달성  또는  약제  부작용  경험  환자진료환경의료기관
1  중재/실행지표                              약제의  종류를  변경
2     비교지표                        약제의  종류를  변경하지  않음
3      결과물                    심뇌혈관질환의  예방  및  재발  방지

page : 93

         0                                1
0  권고  적용군  치료  목표  미달성  이상지질혈증  환자진료환경의료기관
1  중재/실행지표                         약제  병용요법
2     비교지표                       단일  약제  요법
3      결과물                       심뇌혈관질환  예방

,0,1,2,3
0,권고 내용,권고등급,근거수준,권고도출 자료원
1, 내약 가능한 최대 용량의 스타틴 사용에도 불구하고 LDL 콜레스테...,I,A,"13, 34-39"
2, 고용량의 스타틴 치료에도 불구하고 LDL 콜레스테롤 치료 목표에 도달하...,IIb,C,"1, 2, 13, 40"
3, 죽상경화성 심혈관질환이 있었던 환자에게 최대 가용 용량의 스타틴 ...,IIa,A,"1, 2, 13-1519, 25, 26, 47, 48"
4, 스타틴과 니코틴산(Nicotinic acid/Niacin)의 병용은 권고...,I,A,"41, 42"
5, 스타틴 치료에 부작용이 있는 경우에는 스타틴 외의 약제(콜레스테롤 흡수억제제(에...,IIb,C,"1, 2, 13, 43,16, 17"
6, 죽상경화성 심혈관질환이나 당뇨병 환자에서 생활 습관 개선 및 스타틴 투약 후에도...,IIb,B,29
7, 죽상경화성 심혈관질환이나 당뇨병 환자에서 생활 습관 개선 및 스타틴 투약 후에도...,IIb,D,49-52
8, 죽상경화성 심혈관질환이나 당뇨병 환자에서 생활 습관 개선 및 스타틴 투약 후에도...,IIb,D,"29, 53"
9, 근병증의 부작용 발생 위험이 높으므로 스타틴과 젬피브로질을 병용하지...,I,C,"2, 44-46, 54"
10, 심혈관질환 고위험군에서 LDL 콜레스테롤이 목표에 도달하였다고 하더라도 중성지방...,IIb,C,"2, 44-46, 52, 55"

page : 94
page : 95
page : 96
page : 97
page : 98

         0                                   1
0  권고  적용군  이상지질혈증으로  약물요법  중인  모든  환자진료환경의료기관
1  중재/실행지표                           약물요법을  지속
2     비교지표                일정  기간의  약물요법  후  중단
3      결과물                      심뇌혈관질환  발생  감소

page : 99
page : 100
page : 101
page : 102
page : 103
page : 104
page : 105

c:\Users\82103\anaconda3\Lib\site-packages\camelot\parsers\lattice.py:397: UserWarning: No tables found on page-104
  warnings.warn(

         0                                                  1
0  권고  적용군        이상지질혈증으로 진단된 관상동맥질환 혹은 급성심근경색 발생 환자진료환경의료기관
1  중재/실행지표           LDL  콜레스테롤  치료  목표로  감소시키기  위한  약물요법  시행
2     비교지표     LDL  콜레스테롤  치료  목표로  감소시키기  위한  약물요법  시행하지  않음
3      결과물  심혈관계  사건(심근경색,  뇌졸중  발생  및  심혈관계  사망  등)  위험도  감소

                                                   0     1     2          3
0                                             권고  내용  권고등급  근거수준  권고도출  자료원
1   관상동맥질환이  있는  환자는  이차  예방을  위해  LDL  콜레스테롤  농...     I     A        1-4
2   급성심근경색증이  발생한  경우  기저치의  LDL  콜레스테롤  농도와  상관...     I     A  2,  3,  4

page : 106
page : 107
page : 108

         0                  1
0  권고  적용군    당뇨병  환자진료환경의료기관
1  중재/실행지표   혈중  지질농도  검사  시행
2     비교지표  혈중  지질농도  검사  미시행
3      결과물         심뇌혈관질환  예방

                                                   0     1     2            3
0                                             권고  내용  권고등급  근거수준    권고도출  자료원
1   유병 기간이 10년 미만이고 주요 심혈관질환 위험인자를 동반하지 않은 당뇨병 환...     I     A          5-9
2   유병 기간이 10년 이상이거나 주요 심혈관질환 위험인자 또는 표적장기손상(알부민...     I     B          5-9
3   표적장기손상이나 3개 이상의 주요 심혈관질환 위험인자를 동반한 당뇨병 환자는 L...   IIa     B          5-9
4      당뇨병  환자에서  이상지질혈증의  일차  약물로  스타틴을  권고한다.a,b)     I     A    6,  10-12
5   최대내약용량(maximum  tolerated  dose)의  스타틴으로  목표...   IIa     B  2,  13,  14
6   심혈관질환이 있는 당뇨병 환자에서 에제티미브를 추가한 후에도 목표치에 도달하지 ...   IIa     B      15,  16

page : 109
page : 110
page : 111
page : 112

         0                                 1
0  권고  적용군  이상지질혈증을  진단받은  만성콩팥병  환자진료환경의료기관
1  중재/실행지표            스타틴을  이용하여  이상지질혈증  조절
2     비교지표   스타틴을  이용하여  이상지질혈증  조절을  하지  않음
3      결과물             심뇌혈관질환으로  인한  사망률  감소

                                                   0     1     2         3
0                                             권고  내용  권고등급  근거수준  권고도출 자료원
1   사구체여과율  저하  또는  알부민뇨  정도가  심할수록  심뇌혈관질환의  위험...     I     A     17-21
2   투석 전 만성콩팥병 3-5단계의 환자에서 심뇌혈관계질환의 위험을 낮추기 위해 스...     I     A     22-25
3   만성콩팥병  1-2단계의  환자에서  연령,  당뇨병,  관상동맥병과  허혈성뇌...   IIa     B   26,  27
4  50세 미만 만성콩팥병 환자에서는 관상동맥질환의 기왕력, 당뇨병, 허혈성 뇌졸중의...   IIa     A        25
5   고중성지방혈증을 가진 성인 만성콩팥병 환자의 경우 일차적으로 치료적 생활 습관의...   IIa     C     28-30

page : 113
page : 114
page : 115

         0                                           1
0  권고  적용군  이상지질혈증을  진단받은  만성콩팥병  5단계의  모든  환자진료환경의료기관
1  중재/실행지표                      스타틴을  이용하여  이상지질혈증  조절
2     비교지표             스타틴을  이용하여  이상지질혈증  조절을  하지  않음
3      결과물                       심뇌혈관질환으로  인한  사망률  감소

                                                   0     1     2             3
0                                             권고  내용  권고등급  근거수준     권고도출  자료원
1   투석이  필요한  만성콩팥병  5단계의  환자에서  기존  사용  중인  스타틴...   IIa     C            25
2   투석  중인  만성콩팥병  5단계의  환자에서  심뇌혈관계질환의  위험을  낮추...     I     A  23,  31,  32
3   신장이식을  시행  받은  성인  만성콩팥병  환자의  경우  스타틴  치료를 ...   IIa     B         33-35

page : 116
page : 117

         0                              1
0  권고  적용군  허혈뇌졸중  및  일과성허혈발작  환자진료환경의료기관
1  중재/실행지표   죽상경화증과  뇌졸중  발병  원인에  대한  평가
2     비교지표                  평가를  진행하지  않음
3      결과물         발병  원인에  따른  허혈뇌졸중  치료

page : 118

         0                                            1
0  권고  적용군  심장성 색전증을 유발할 수 있는 심장질환이 없는 허혈뇌졸중 환자진료환경의료기관
1  중재/실행지표                                 고강도  스타틴  투여
2     비교지표                                스타틴  투여하지  않음
3      결과물                                  뇌졸중  발생  감소

                                                   0     1     2          3
0                                             권고  내용  권고등급  근거수준  권고도출  자료원
1   허혈뇌졸중 환자가 심혈관질환 및 심장성 색전증을 일으킬 수 있는 질환이 없고, ...     I     A         36

page : 119

         0                                            1
0  권고  적용군  죽상경화증을  동반한  허혈뇌졸중  또는  일과성허혈발작  환자진료환경의료기관
1  중재/실행지표             LDL  콜레스테롤을  70  mg/dL  미만으로  저하
2     비교지표              LDL  콜레스테롤을  90-110  mg/dL로  저하
3      결과물                               심뇌혈관질환  발생  감소

                                                   0     1     2          3
0                                             권고  내용  권고등급  근거수준  권고도출  자료원
1   뇌동맥,  목동맥, 대동맥에  죽상경화증이  있는  허혈뇌졸중  환자는  심뇌혈...     I     A    37,  38

page : 120

         0                                    1
0  권고  적용군        고위험  죽상경화성  허혈뇌졸중  환자진료환경의료기관
1  중재/실행지표     LDL  콜레스테롤을  55  mg/dL  미만으로  저하
2     비교지표  LDL  콜레스테롤을  55-70  mg/dL  미만으로  저하
3      결과물                        허혈뇌졸중  발생  감소

                                                   0     1     2          3
0                                             권고  내용  권고등급  근거수준  권고도출  자료원
1   재발 위험이 높은 죽상경화성 허혈뇌졸중 및 일과성허혈발작 환자는 LDL 콜레스테...   IIa     B    39,  40

page : 121
page : 122

         0                                                1
0  권고  적용군  이상지질혈증으로  진단된  노인  환자(65세  이상  75세  이하)진료환경의료기관
1  중재/실행지표                       이상지질혈증에  대해  스타틴  약물요법  시행
2     비교지표                 이상지질혈증에  대해  스타틴  약물요법  시행하지  않음
3      결과물                         심뇌혈관질환의  이환율  및  사망률  감소

,0,1,2,3
0,권고 내용,권고등급,근거수준,권고도출 자료원
1, 심뇌혈관질환을 동반한 75세 이하 노인 환자에서 이차 예방을 위한 지질강하제의 ...,I,A,41-52
2, 심뇌혈관질환을 진단받지 않은 75세 이하 노인 환자에서 일차 예방...,I,B,"2, 41-46, 48, 53"
3, 노인 환자에서는 다른 질환들이 동반되어 있을 수 있고 약동학적 특성의 변화가 있...,I,D,"41, 46, 49, 51-64"

page : 123
page : 124

         0                                       1
0  권고  적용군  이상지질혈증으로  진단된  노인  환자(75세  초과)진료환경의료기관
1  중재/실행지표              이상지질혈증에  대해  스타틴  약물요법  시행
2     비교지표        이상지질혈증에  대해  스타틴  약물요법  시행하지  않음
3      결과물                심뇌혈관질환의  이환율  및  사망률  감소

,0,1,2,3
0,권고 내용,권고등급,근거수준,권고도출 자료원
1, 심뇌혈관질환을 동반한 75세 초과 노인 환자에서 이차 예방을 위해...,IIa,B,"14, 44, 46, 54, 63, 65-82"
2, 심뇌혈관질환을 동반하지 않은 75세 초과 노인 환자에서 당뇨병이 ...,IIa,C,"54, 83-93"
3," 노인 환자에서는 다른 질환들이 동반되어 있을 수 있고, 약동학적 특성의 변화가 ...",I,D,"41, 46, 49, 51-63"

page : 125
page : 126

         0                    1
0  권고  적용군  임신부  및  수유부진료환경의료기관
1  중재/실행지표              스타틴  중지
2     비교지표              스타틴  지속
3      결과물    산모  및  태아  건강  유지

                                                   0     1     2           3
0                                             권고  내용  권고등급  근거수준   권고도출  자료원
1   임신 중 고혈압 질환-전자간증(preeclampsia)-의 합병증을 경험한 여성...     I     A     94,  95
2   임신부의 고중성지방혈증은 신생아 체중 증가, 거대아 위험도 증가와 연관이 있으므...    Ⅱa     A      96-101
3   임신 중 고콜레스테롤혈증을 치료하는 것이 임신부 건강에 유익하다는 확실한 증거가...     I     A  54,102-105

page : 127
page : 128

         0                                                  1
0  권고  적용군  생활 습관을 교정한 후에도 LDL 콜레스테롤 농도가 높은 가족성 진료환경의료기관고콜...
1  중재/실행지표               약물을  투여하여  LDL  콜레스테롤  치료  목표로  감소시킴
2     비교지표      LDL  콜레스테롤  치료  목표로  감소시키기  위한  약물을  투여하지  않음
3      결과물                                    심뇌혈관질환  위험도  감소

,0,1,2,3
0,권고 내용,권고등급,근거수준,권고도출 자료원
1, 가족성 고콜레스테롤혈증 환자는 LDL 콜레스테롤 수치를 낮추기 위해...,I,B,"41-43,106-111"
2, 일반 환자에 비해서 목표치에 도달하기 어려울 수 있으므로 기저치에...,IIa,B,"41-43,106-109, 112"

page : 129
page : 130

         0                                                  1
0  권고  적용군  약물을  투여한  후에도  LDL  콜레스테롤  농도가  치료  목표로 진료환경의료...
1  중재/실행지표  약물의  용량을  최대한  증량시키거나  병용하여  기저치보다  50%  이상  감소시킴
2     비교지표    기저치보다  50%  이상  감소시키기  위한  약물  증량  또는  병용하지  않음
3      결과물                                    심뇌혈관질환  위험도  감소

,0,1,2,3
0,권고 내용,권고등급,근거수준,권고도출 자료원
1, 스타틴을 최대용량으로 투여한 후에도 LDL 콜레스테롤 농도가 치료 ...,I,A,"41-43,106-111"
2, 스타틴을 최대용량으로 투여한 후에도 LDL 콜레스테롤 농도가 치료 목표 미...,IIa,B,"41-43,106-110, 112-114"
3, 심뇌혈관질환이 있거나 심뇌혈관질환 발생위험이 높은 경우(추가적인 위험...,IIa,C,"3, 4, 114-133"

page : 131

         0   1                             2                             3
0  콜레스테롤수치                                TC                         LDL-C
1           소아  ＞  6.7  mmol/L  (260  mg/dL)  ＞  4.0  mmol/L  (155  mg/dL)
2           성인  ＞  7.5  mmol/L  (290  mg/dL)  ＞  4.9  mmol/L  (190  mg/dL)

page : 132

                                                   0
0                                소아청소년의  이상지질혈증의  치료
1  1) 소아의  이상지질혈증  치료는  성인에서와  마찬가지로  적극적인  생활  습...

,0,1,2,3,4,5
0,HMG-CoA환원효소억제제(스타틴),Atorvastatin,5-10 mg,20 mg,80 mg,승인
1,,Fluvastatin,20 mg,80 mg,80 mg,승인
2,,Lovastatin,10 mg,40 mg,80 mg,승인
3,,Pravastatin,10 mg,40 mg (14-18세)20 mg (8-13세),80 mg,승인
4,,Rosuvastatin,5 mg,20 mg,40 mg,승인
5,,Simvastatin,10 mg (10세 이상)5 mg (10세),40 mg,40 mg,승인
6,콜레스테롤흡수억제제,Ezetimibe,10 mg,10 mg,10 mg,승인
7,피브린산유도체,Gemfibrozil,"1,200 mg",데이터 부족,"1,200 mg",비승인
8,,Fenofibrate,40 mg,데이터 부족,130-200 mg,비승인
9,담즙산제거제,Cholestyramine,2-4 g 혹은240 mg/kg/일,8 g4 g (10세 미만),16 g,승인
10,,Colestipol,2.5-5 g,12 g,20 g,비승인
11,,Colesevelam,1.25 g,3.75 g,3.75 g,제한적 승인
12,오메가-3지방산,Omega-3-acid ethyl esters,1 g,데이터 부족,4 g,비승인

page : 133
page : 134
page : 135
page : 136
page : 137
page : 138
page : 139
page : 140
page : 141
page : 142
page : 143